schema_version: 1

context:
  name: module-qc-analysis-tools
  version: "2.6.4"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/module_qc_analysis_tools-${{ version }}.tar.gz
  sha256: 0401be222e750b5d0f875ba14e2fc421fdf686f2eae06eb1141c215c306521b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - module-qc-analysis-tools = module_qc_analysis_tools.cli:app
      - mqat = module_qc_analysis_tools.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy
    - matplotlib-base
    - module-qc-tools >=2.6.0
    - module-qc-data-tools >=1.3.0
    - module-qc-database-tools >=2.7.0
    - typer
    - scipy
    - arrow

tests:
  - python:
      imports:
        - module_qc_analysis_tools
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - mqat --help
      - mqat --version
      - module-qc-analysis-tools --help
      - module-qc-analysis-tools --version

about:
  summary: Module qc analysis tools
  homepage: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-analysis-tools
  repository: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-analysis-tools
  documentation: https://atlas-itk-pixel-mqat.docs.cern.ch/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - elisabettapianori
    - marijamarjanovic
    - lime86
